from infra.conf.environ import env

DEFAULT_FILE_STORAGE = "core.storage_backends.FileStorage"

FILE_STORAGE_ACCESS_KEY = env("FILE_STORAGE_ACCESS_KEY", str, "minioaccess")
FILE_STORAGE_SECRET_KEY = env("FILE_STORAGE_SECRET_KEY", str, "miniosecret")
FILE_STORAGE_HOST = env("FILE_STORAGE_HOST", str, "localhost")
FILE_STORAGE_PORT = env("FILE_STORAGE_PORT", int, 9000)
FILE_STORAGE_USE_SSL = env("FILE_STORAGE_USE_SSL", bool, False)
FILE_STORAGE_FRONTEND_HOST = env("FILE_STORAGE_FRONTEND_HOST", str, "localhost")
FILE_STORAGE_BUCKET_NAME = env("FILE_STORAGE_BUCKET_NAME", str, "journal")
FILE_STORAGE_OBJECT_PREFIX = env("FILE_STORAGE_OBJECT_PREFIX", str, "c")

AWS_QUERYSTRING_AUTH = env("AWS_QUERYSTRING_AUTH", bool, False)
AWS_QUERYSTRING_EXPIRE = env("AWS_QUERYSTRING_EXPIRE", int, 0)
